/* Generated by Cython 0.29.32 */

#ifndef __PYX_HAVE__octobot__updater__updater_factory
#define __PYX_HAVE__octobot__updater__updater_factory

#include "Python.h"

#ifndef __PYX_HAVE_API__octobot__updater__updater_factory

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *__pyx_f_7octobot_7updater_15updater_factory_create_updater(int __pyx_skip_dispatch);

#endif /* !__PYX_HAVE_API__octobot__updater__updater_factory */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initupdater_factory(void);
#else
PyMODINIT_FUNC PyInit_updater_factory(void);
#endif

#endif /* !__PYX_HAVE__octobot__updater__updater_factory */
